spring:
  datasource:
    url: jdbc:postgresql://localhost:5452/event
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: http://localhost:9092

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    com.mayosen.financeapp: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.apache.kafka: WARN
