spring:
  application:
    name: command-service
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  kafka:
    events:
      topic: financeapp-events
  snapshot:
    strategy:
      every-times: 5

logbook:
  format:
    style: curl

logging:
  level:
    org.zalando: TRACE
