openapi: 3.0.1
info:
  title: Query API
  description: API for account queries
  version: 1.0.0
tags:
  - name: query
    description: Query API
paths:
  /api/v1/queries/accounts:
    get:
      tags:
        - query
      summary: List accounts by owner
      operationId: listAccounts
      parameters:
        - name: ownerId
          in: query
          required: true
          schema:
            type: string
          example: "user123"
      responses:
        '200':
          description: Accounts list retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAccountsResponse'

  /api/v1/queries/accounts/{accountId}:
    get:
      tags:
        - query
      summary: Get account summary
      operationId: getAccountSummary
      parameters:
        - $ref: '#/components/parameters/accountId'
      responses:
        '200':
          description: Account summary retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountSummaryResponse'

  /api/v1/queries/accounts/{accountId}/transactions:
    get:
      tags:
        - query
      summary: Get transaction history
      operationId: getTransactions
      parameters:
        - $ref: '#/components/parameters/accountId'
        - name: timeFrom
          in: query
          required: false
          schema:
            type: string
            format: date-time
          example: "2025-01-01T00:00:00Z"
        - name: timeTo
          in: query
          required: false
          schema:
            type: string
            format: date-time
          example: "2025-01-31T23:59:59Z"
        - name: pageOffset
          in: query
          required: false
          schema:
            type: integer
            default: 0
          example: 0
        - name: pageLimit
          in: query
          required: false
          schema:
            type: integer
            default: 20
          example: 20
      responses:
        '200':
          description: Transaction history retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTransactionHistoryResponse'

components:
  parameters:
    accountId:
      name: accountId
      in: query
      required: true
      schema:
        type: string
      example: "e1be0f53-007a-4d58-805b-2c5a64fd3ff4"

  schemas:
    ListAccountsResponse:
      type: object
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'
      required:
        - accounts

    Account:
      type: object
      properties:
        accountId:
          type: string
          example: "e1be0f53-007a-4d58-805b-2c5a64fd3ff4"
        balance:
          $ref: '#/components/schemas/DecimalAmount'
        updatedAt:
          type: string
          format: date-time
          example: "2025-05-15T12:34:56Z"
      required:
        - accountId
        - balance
        - updatedAt

    GetAccountSummaryResponse:
      type: object
      properties:
        accountId:
          type: string
          example: "e1be0f53-007a-4d58-805b-2c5a64fd3ff4"
        balance:
          $ref: '#/components/schemas/DecimalAmount'
        ownerId:
          type: string
          example: "user123"
        updatedAt:
          type: string
          format: date-time
          example: "2025-05-15T12:34:56Z"
      required:
        - accountId
        - balance
        - ownerId
        - updatedAt

    GetTransactionHistoryResponse:
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        pagination:
          $ref: '#/components/schemas/Pagination'
      required:
        - transactions
        - pagination

    Transaction:
      type: object
      properties:
        transactionId:
          type: string
          example: "e1be0f53-007a-4d58-805b-2c5a64fd3ff4"
        type:
          $ref: '#/components/schemas/TransactionType'
        amount:
          $ref: '#/components/schemas/DecimalAmount'
        timestamp:
          type: string
          format: date-time
          example: "2025-05-15T12:34:56Z"
        relatedAccountId:
          type: string
          nullable: true
          example: "e1be0f53-007a-4d58-805b-2c5a64fd3ff4"
      required:
        - transactionId
        - type
        - amount
        - timestamp

    TransactionType:
      type: string
      enum:
        - DEPOSIT
        - WITHDRAWAL
        - TRANSFER_OUT
        - TRANSFER_IN

    Pagination:
      type: object
      properties:
        hasMore:
          type: boolean
          example: false
        total:
          type: integer
          example: 15
      required:
        - hasMore
        - total

    DecimalAmount:
      type: string
      format: decimal
      example: "50.00"
