@startuml C4_Context
!include <c4/C4_Context.puml>

LAYOUT_LEFT_RIGHT()

'skinparam nodesep 20
skinparam ranksep 15
'skinparam Padding 8
'scale max 1024 width

' Определение участников и систем
Person(user, "Пользователь", "Клиентское приложение")
System(commandService, "Command Service", "Обрабатывает команды, сохраняет события")
System(eventBus, "Event Bus", "Шина событий для передачи событий между сервисами")
System(queryService, "Query Service", "Строит проекции для чтения данных")

' Отношения между элементами
Rel(user, commandService, "Отправляет команды")
Rel(commandService, eventBus, "Публикует события")
Rel(eventBus, queryService, "Доставляет события")
Rel(user, queryService, "Отправляет запросы на чтение")

@enduml
