name: Build Query Service

on:
  push:
    paths:
      - 'query-service/**'
      - 'common/**'
      - 'pom.xml'
  pull_request:
    paths:
      - 'query-service/**'
      - 'common/**'
      - 'pom.xml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Compile module
        run: mvn -pl query-service -am test-compile

      - name: Archive compiled classes
        uses: actions/upload-artifact@v4
        with:
          name: query-service-compiled
          path: |
            **/target/classes
            **/target/test-classes
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Download compiled classes
        uses: actions/download-artifact@v4
        with:
          name: query-service-compiled

      - name: Run tests
        run: mvn -pl query-service -am verify

      - name: Archive test reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: query-test-reports
          path: |
            **/target/surefire-reports/
            **/target/failsafe-reports/
